// -- Services
export const HOME_FETCH_SUCCESS = 'home_fetch_success';
export const FILL_USER_DATA = 'fill_user_data';
export const TEST_CONNECTION = 'TEST_CONNECTION';
export const FETCH_CATEGORY_OPNED_SERVICES = 'fetch_category_opened_services';
export const CLEAR_OPENED_CAT_SERVICES = 'clear_opened_cat_services';
export const SET_SERVICE_MANIPULATION_INTERVAL =
  'SET_SERVICE_MANIPULATION_INTERVAL';
export const SET_BLOCKED_SERVICES = 'SET_BLOCKED_SERVICES';
export const SET_SERVICES_REVIEW = 'SET_SERVICES_REVIEW';

// Favorites
export const FETCH_Favorites_SUCCESS = 'FETCH_Favorites_SUCCESS';
export const INSERT_FAVORITE = 'INSERT_FAVORITE';
export const FETCH_Favorites_FAILURE = 'FETCH_Favorites_FAILURE';

// Slots
export const FETCH_Slots_SUCCESS = 'FETCH_Slots_SUCCESS';
export const Slots_TIMEZONE_ADJUSTMENT = 'Slots_TIMEZONE_ADJUSTMENT';

// NotRatedCalls
export const FETCH_NotRatedCalls_SUCCESS = 'FETCH_NotRatedCalls_SUCCESS';

// Countries
export const SET_COUNTRIES = 'SET_COUNTRIES';

// -- New Services
export const SERVICES_FETCH_SUCCESS = 'SERVICES_FETCH_SUCCESS';
export const SERVICES_ONOFFLINE = 'servicesonlineoffline';
export const SERVICESCOSTS_FETCH_SUCCESS = 'SERVICESCOSTS_FETCH_SUCCESS';
export const SERVICESPHONES_FETCH_SUCCESS = 'SERVICESPHONES_FETCH_SUCCESS';
export const CLEAR_SERVICES = 'CLEAR_SERVICES';
export const SERVICE_USER_AUTHORIZED = 'SERVICE_USER_AUTHORIZED';

// -- New Slides
export const SLIDES_FETCH_SUCCESS = 'SLIDES_FETCH_SUCCESS';
export const SLIDES_FETCH_FAILED = 'SLIDES_FETCH_FAILED';
export const FETCH_APP_DATA = 'FETCH_APP_DATA';

// -- New Categories
export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS';
export const OPENED_CAT_CHANGED = 'OPENED_CAT_CHANGED';

// -- New Lecturers
export const LECTURERS_FETCH_SUCCESS = 'LECTURERS_FETCH_SUCCESS';

// -- New ServiceLecturers
export const SERVICES_LECTURERS_FETCH_SUCCESS =
  'SERVICES_LECTURERS_FETCH_SUCCESS';

//Auth

export const USER_FETCH_SUCCESS = 'user_fetch_success';
export const LOGOUT = 'logout';

// Logs
export const FETCH_LOGS = 'FETCH_LOGS';
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS';
export const FETCH_LOGS_FAILURE = 'FETCH_LOGS_FAILURE';

//Log Details
export const FETCH_LOG_DETAILS = 'FETCH_LOG_DETAILS';
export const FETCH_LOG_DETAILS_SUCCESS = 'FETCH_LOG_DETAILS_SUCCESS';
export const FETCH_LOG_DETAILS_FAILURE = 'FETCH_LOG_DETAILS_FAILURE';

// Balance
export const FETCH_BALANCE = 'FETCH_BALANCE';
export const FETCH_BALANCE_SUCCESS = 'FETCH_BALANCE_SUCCESS';
export const FETCH_BALANCE_FAILURE = 'FETCH_BALANCE_FAILURE';
export const FETCH_TRANSACTION_LOG_SUCCESS = 'FETCH_TRANSACTION_LOG_SUCCESS';
export const FETCH_TRANSACTION_LOG_FAILURE = 'FETCH_TRANSACTION_LOG_FAILURE';

// Update User
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';

// Lecturer
export const FETCH_LECTURER = 'FETCH_LECTURER';
export const FETCH_LECTURER_SUCCESS = 'FETCH_LECTURER_SUCCESS';
export const FETCH_LECTURER_FAILURE = 'FETCH_LECTURER_FAILURE';

// Chat Rooms
export const FETCH_CHAT_ROOMS = 'FETCH_CHAT_ROOMS';
export const FETCH_CHAT_ROOMS_SUCCESS = 'FETCH_CHAT_ROOMS_SUCCESS';
export const FETCH_CHAT_ROOMS_FAILURE = 'FETCH_CHAT_ROOMS_FAILURE';
export const SET_PENDING_MESSAGES = 'SET_PENDING_MESSAGES';
export const CLEAR_PENDING_MESSAGES = 'CLEAR_PENDING_MESSAGES';
export const SET_CURRENT_ROOMID = 'SET_CURRENT_ROOMID';

// Chat Users
export const FETCH_CHAT_USERS = 'FETCH_USER_FETCH_CHAT_USERSROOMS';
export const FETCH_CHAT_USERS_SUCCESS = 'FETCH_CHAT_USERS_SUCCESS';
export const FETCH_CHAT_USERS_FAILURE = 'FETCH_CHAT_USERS_FAILURE';

// Messages
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';

// Block
export const SET_BLOCKED_USERS = 'SET_BLOCKED_USERS';

export const SWITCH_ACCOUNT = 'SWITCH_ACCOUNT';

export const SET_INTERNET_CONNECTION = 'SET_INTERNET_CONNECTION';

export const SET_EARININGS = 'SET_EARININGS';
export const SET_COMMISSION = 'SET_COMMISSION';
export const SET_INVITED_USERS_COMMISSION = 'SET_INVITED_USERS_COMMISSION';

// APP
export const UPDATE_DRAWER_STATUS = 'UPDATE_DRAWER_STATUS';
export const SET_APP_INTRO = 'SET_APP_INTRO';
export const SET_APP_CONFIG = 'SET_APP_CONFIG';
export const SET_TESTING_MODE = 'SET_TESTING_MODE';
export const SET_COMPLAINTS = 'SET_COMPLAINTS';
export const GET_APP_TOUR_STATUS = 'GET_APP_TOUR_STATUS';
export const SET_NOTCH = 'SET_NOTCH';

//Rates
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS';

// Call Requests
export const SET_CALL_REQUESTS = 'SET_CALL_REQUESTS';
export const SET_CALL_REQUESTS_FETCH_ERROR = 'SET_CALL_REQUESTS_FETCH_ERROR';

export const SET_FCM_TOKEN = 'SET_FCM_TOKEN';

export const SET_TRANSLATION = 'SET_TRANSLATION';

export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_NOTIFICATIONS_FETCH_ERROR = 'SET_NOTIFICATIONS_FETCH_ERROR';

export const SET_PRICES = 'SET_PRICES';

//Themes
export const SET_THEMES = 'SET_THEMES'

export const SET_MIN_SUPPORTED_VERSION = 'SET_MIN_SUPPORTED_VERSION'

//Support chat
export const SET_MESSAGES = 'SET_MESSAGES'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'
export const SET_UNREAD_COUNT = 'SET_UNREAD_COUNT'
export const SET_OPPONENT = 'SET_OPPONENT'
export const SET_INITIATED = 'SET_INITIATED'
export const SET_EXPANDED = 'SET_EXPANDED'
export const SET_DIALOG = 'SET_DIALOG'
export const SET_LOADING = 'SET_LOADING'
export const SET_TYPING = 'SET_IS_TYPING'
export const SET_CHATS = 'SET_CHATS'
export const SET_OPEN_CHATS_LIST = 'SET_OPEN_CHATS_LIST'
export const SET_UPLOADING = 'SET_UPLOADING'
export const SET_READ = 'SET_READ'
export const SET_IS_SUPPORT = 'SET_IS_SUPPORT'
export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT'
export const SET_DELIVERED = 'SET_DELIVERED'
export const SET_AUTO_INIT = 'SET_AUTO_INIT'
export const CHANGE_VISIBILITY = 'CHANGE_VISIBILITY'
